### ISSUE TITLE
Grafana Dashboard URL ?

### ISSUE THREAD

**Issue by NeWoKiKi** [matt-FFFFFF/hassio-addon-teslamate#106]
Hi,

I've just installed you addon that is really cool !
I had to fix 2 little things like adding pluggins to remove some errors and to get dashboard fully fonctional :

```
plugins:
  - natel-discrete-panel
  - pr0ps-trackmap-panel
  - grafana-piechart-panel
  - natel-plotly-panel
custom_plugins:
  - name: panodata-map-panel
    url: >-
      https://github.com/panodata/panodata-map-panel/releases/download/0.16.0/panodata-map-panel-0.16.0.zip
    unsigned: true
```

But one thing I haven't found :
Which URL should I set in Grafana Dashboard field in Teslamate settings to get dashboard link directly from Teslamate ?

![image](https://github.com/matt-FFFFFF/hassio-addon-teslamate/assets/69678428/b242793a-ed94-494d-9f4b-b54cfd0b4c04)

Many thanks for your help
Regards,
