### ISSUE TITLE
I only see Tesla maps

### ISSUE THREAD

**Issue by bozzomasterflash** [matt-FFFFFF/hassio-addon-teslamate#45]
I installed and I don't see errors in the logs, but if I open TeslaMate and log in with tesla account, I only see the screen where the see the position of Tesla with the information, nothing else. 
Where am I wrong

**Comment by matt-FFFFFF** [comment]
Hi, Teslamate writes its data to a database and then Grafana is used to display this data in a pretty format. You need Grafana and to configure the addon to upload the reports to Grafana on startup.

**Comment by bozzomasterflash** [comment]
ok, clear, I was missing some pieces.
Help me understand where I need to go for this section: Automatically Uploading Grafana Dashboards

**Comment by giggo** [comment]
This is what I get too:
[08:41:58] INFO: Checking for Grafana folder: TeslaMate
jq: error (at :0): Cannot index string with string "title"

Any idea what is missing in my Grafana configuration? I do have a datasource called "TeslaMate"

**Comment by matt-FFFFFF** [comment]
Either the Grafana username, password, host or port are incorrect in the **teslamate** addon configuration

```yaml
grafana_host: a0d7b954-grafana   # this is correct if you use the community addon
grafana_port: 3000               # this is correct if you use the community addon
grafana_user: admin
grafana_pass: mysecretpassword
```

When you configure Grafana with the `GF_SECURITY_ADMIN_PASSWORD` and `GF_SECURITY_ADMIN_USER` you might have to delete the Grafana addon and re-install. Make sure the configuration contains these environment variables the first time the Grafana addon starts.
