### ISSUE TITLE
MQTT Sensor Teslamate shows Unknown

### ISSUE THREAD

**Issue by LowKey88** [matt-FFFFFF/hassio-addon-teslamate#76]
Hi,

I've created the tesla.yaml

https://pastebin.com/7GHrKR3C

<img width="506" alt="Screenshot 2022-10-09 at 10 06 53 PM" src="https://user-images.githubusercontent.com/1294172/194761347-a23c89ef-62c4-4d4b-90ae-033e1cc5bd14.png">

Added the sensors to lovelace, but seem it's shows to "Unknown"

How to get it's can be read properly from MQTT? 

I'm successfully installed hassio-addon-teslamate on my homeassistant. Able to see all the data from Grafana.

Kindly help.

Thank you

**Comment by matt-FFFFFF** [comment]
Hi,

How is your MQTT configured?

I have this entry in my `tesla.yaml`


```yaml
- platform: mqtt
  name: tesla_since
  state_topic: "teslamate/cars/1/since"
  icon: mdi:clock-outline
```
